name: backend
description: Dart server for Todo App.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  args: ^2.0.0
  google_cloud: ^0.2.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  http: ^1.0.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.0
  shared: ^1.0.0


dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.1.0
  mocktail: ^1.0.4
  test: ^1.24.0
