name: shared
description: Shared models types for the Todo application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.5
  json_serializable: ^6.11.4
  test: ^1.24.0
  lints: ^6.0.0
  coverage: ^1.15.0
